# Generated by Django 4.1.7 on 2025-01-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_learning', '0005_employee_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee_learning.division'),
            preserve_default=False,
        ),
    ]
